# Generated by Django 5.0.7 on 2024-08-06 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_purchase_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='children',
            new_name='parent',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.category'),
            preserve_default=False,
        ),
    ]
