# Generated by Django 5.0.7 on 2024-08-06 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='nikname',
            new_name='nickname',
        ),
    ]
